version: '3'
services:
    idx:
        image: splunk/splunk
        hostname: idx
        tty: true
        ports:
            - "8000"
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    ds:
        image: splunk/splunk
        hostname: ds 
        tty: true
        ports:
            - "8000"
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    hf1:
        image: splunk/splunk
        hostname: hf1
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    hf2:
        image: splunk/splunk    
        hostname: hf2
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    hf3:
        image: splunk/splunk    
        hostname: hf3
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    hf4:
        image: splunk/splunk    
        hostname: hf4
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    hf5:
        image: splunk/splunk    
        hostname: hf5
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license --answer-yes
            SPLUNK_PASSWORD: splunk01
    uf1:
        image: splunk/universalforwarder
        hostname: uf1
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: splunk01
    uf2:
        image: splunk/universalforwarder
        hostname: uf2
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: splunk01
    uf3:
        image: splunk/universalforwarder
        hostname: uf3
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: splunk01
    uf4:
        image: splunk/universalforwarder
        hostname: uf4
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: splunk01
    uf5:
        image: splunk/universalforwarder
        hostname: uf5
        tty: true
        networks:
            - splunk-lsm
        environment:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: splunk01
    lsmadmin:
        build: lsmadmin
        hostname: lsmadmin
        tty: true
        ports:
            - "8080"
        networks:
            - splunk-lsm
    ldap:
        image: osixia/openldap
        hostname: ldap
        tty: true
        ports: 
            - "389"
            - "636"
        networks:
            - splunk-lsm
    ldapadmin:
        image: osixia/phpldapadmin
        hostname: ldapadmin
        tty: true
        ports:
            - "443"
        networks:
            - splunk-lsm
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap

networks:
    splunk-lsm:

