pack:
	cd ..; tar --exclude=static/*.pem --exclude=lookups/lookup_file_backups --exclude=lookups/.gitkeep --exclude=lookups/*.csv --exclude=local/* --exclude=.git --exclude=.gitignore --exclude=Makefile -s /\.csv\.default/\.csv/ -cvzf DA-lsm.tar.gz DA-lsm
